### PR TITLE
Fix case where legend is placed over two subplots

### PR DESCRIPTION
**Pull request by SyamGadde**
This addresses #41 (at least in the cases where I trigger a similar error).

### CODE REVIEW

**Comment by wiheto** [comment]
Hi, 

Thanks a lot for this!

Seems to work from my testing and no errors. 

Could you perhaps write a quick comment above regarding your logic? (just so people seeing the slice function in the future understand why it is there).

**Comment by SyamGadde** [comment]
Sure thing, added a comment.

**Comment by wiheto** [comment]
Thanks. lgtm

**Comment by wiheto** [comment]
Hi again, 

Thanks for contributing to NetPlotBrain. 

Feel free to add your name, orcid, and affiliation to the contributor list in .zenodo.json if you want to be listed as a contributor to NetPlotBrain in the Zenodo DOI.

**Pull request merged**
