### PR TITLE
warning for rendering of template style filled and figures for tutorial

### PR DESCRIPTION
**Pull request by silviafan**

### CODE REVIEW

**Review by wiheto — COMMENTED** [review]
So I made one small change to the code and changed the warning statement a bit. 

You have uploaded 3 figures for the documentation but no markdown or python file?  Did you forget something?

**Comment by silviafan** [comment]
Perfect. I am waiting for the branch to be merged so that the figures get added to the folder for the markdown.

**Comment by wiheto** [comment]
The figures will get generated in the markdown folder if it is formatted as notebook The "figures" folder is for static images to show in the gallery main page.

**Comment by wiheto** [comment]
But LGTM and do the documentation how you think it should be done

**Pull request merged**
